# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создан?'),
        ),
    ]
